services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tetris_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PHX_HOST: localhost
      PHX_SERVER: "true"
      MIX_ENV: docker
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    stdin_open: true
    tty: true

volumes:
  postgres_data: